exec: ../dist/build/photosorter/photosorter
args:
    - production
host: 192.168.0.2
postgres: true

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
copy-to: /opt/keter/incoming
