Default: &defaults
  database: photosorter.sqlite3
  poolsize: 1

Development:
  <<: *defaults

Testing:
  database: photosorter_test.sqlite3
  <<: *defaults

Staging:
  database: photosorter_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: photosorter_production.sqlite3
  poolsize: 100
  <<: *defaults
